title: Python-Microservice
description: "DOITNOW!"
remote_theme: just-the-docs/just-the-docs

url: https://cloud-native-engineering.github.io/sem03_docs

aux_links:
  Projektplanung: 

footer_content: "2024 Marc Hofstetter"


