title: Python-Microservice
description: "DOITNOW!"
remote_theme: just-the-docs/just-the-docs

url: https://krkiso.github.io/DOITNOW/

aux_links:
  Projektplanung: 

footer_content: "2024 Marc Hofstetter"