title: Python-Microservice
description: "DOITNOW!"
remote_theme: just-the-docs/just-the-docs

url: https://krkiso.github.io/DOITNOW/

aux_links:
  JIRA Projekt: https://marconline99.atlassian.net/jira/software/projects/DOIT/boards/34/timeline

footer_content: "2024 Marc Hofstetter Sem03 für Technische Berufsschule Zürich, Lehrgang Cloud Native Engineer"